### ISSUE TITLE
node-gyp build fails

### ISSUE THREAD

**Issue by SabeehKhan18** [MakarenaLabs/Shared-Memory-NodeJS-Demo-Server#1]
I was unable to build the example after 'node-gyp build --debug'. I'm not sure if i'm missing a dependency or the example itself does not compile. 

> gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@12.21.0 | linux | arm64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Debug', '-C', 'build' ]
make: Entering directory '/home/root/shm_test/Shared-Memory-NodeJS-Demo-Server/s                           hmnode/build'
  CXX(target) Debug/obj.target/shmnode/shm.o
../shm.cpp: In function 'void ReadSHM(const v8::FunctionCallbackInfo<v8::Value>&                           )':
../shm.cpp:71:63: warning: 'static v8::Local<v8::String> v8::String::NewFromUtf8                           (v8::Isolate*, const char*, v8::String::NewStringType, int)' is deprecated: Use                            maybe version [-Wdeprecated-declarations]
   71 |     args.GetReturnValue().Set(String::NewFromUtf8(isolate, shm));
      |                                                               ^
In file included from /home/root/.cache/node-gyp/12.21.0/include/node/v8-interna                           l.h:14,
                 from /home/root/.cache/node-gyp/12.21.0/include/node/v8.h:27,
                 from ../shm.cpp:1:
/home/root/.cache/node-gyp/12.21.0/include/node/v8.h:3032:21: note: declared her                           e
 3032 |       Local<String> NewFromUtf8(Isolate* isolate, const char* data,
      |                     ^~~~~~~~~~~
/home/root/.cache/node-gyp/12.21.0/include/node/v8config.h:328:3: note: in defin                           ition of macro 'V8_DEPRECATED'
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../shm.cpp:71:63: warning: 'static v8::Local<v8::String> v8::String::NewFromUtf8                           (v8::Isolate*, const char*, v8::String::NewStringType, int)' is deprecated: Use                            maybe version [-Wdeprecated-declarations]
   71 |     args.GetReturnValue().Set(String::NewFromUtf8(isolate, shm));
      |                                                               ^
In file included from /home/root/.cache/node-gyp/12.21.0/include/node/v8-interna                           l.h:14,
                 from /home/root/.cache/node-gyp/12.21.0/include/node/v8.h:27,
                 from ../shm.cpp:1:
/home/root/.cache/node-gyp/12.21.0/include/node/v8.h:3032:21: note: declared her                           e
 3032 |       Local<String> NewFromUtf8(Isolate* isolate, const char* data,
      |                     ^~~~~~~~~~~
/home/root/.cache/node-gyp/12.21.0/include/node/v8config.h:328:3: note: in defin                           ition of macro 'V8_DEPRECATED'
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../shm.cpp: At global scope:
../shm.cpp:77:11: error: variable or field 'init' declared void
   77 | void init(Handle<Object> exports)
      |           ^~~~~~
../shm.cpp:77:11: error: 'Handle' was not declared in this scope
../shm.cpp:77:24: error: expected primary-expression before '>' token
   77 | void init(Handle<Object> exports)
      |                        ^
../shm.cpp:77:26: error: 'exports' was not declared in this scope
   77 | void init(Handle<Object> exports)
      |                          ^~~~~~~
In file included from ../shm.cpp:2:
../shm.cpp:83:22: error: 'init' was not declared in this scope; did you mean 'in                           t'?
   83 | NODE_MODULE(shmnode, init)
      |                      ^~~~
/home/root/.cache/node-gyp/12.21.0/include/node/node.h:737:36: note: in definiti                           on of macro 'NODE_MODULE_X'
  737 |       (node::addon_register_func) (regfunc),                          \
      |                                    ^~~~~~~
../shm.cpp:83:1: note: in expansion of macro 'NODE_MODULE'
   83 | NODE_MODULE(shmnode, init)
      | ^~~~~~~~~~~
make: *** [shmnode.target.mk:103: Debug/obj.target/shmnode/shm.o] Error 1
make: Leaving directory '/home/root/shm_test/Shared-Memory-NodeJS-Demo-Server/sh                           mnode/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/bu                           ild.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces                           s.js:276:12)
gyp ERR! System Linux 5.10.65-gdcc6bedb2c
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "build" "--debug"
gyp ERR! cwd /home/root/shm_test/Shared-Memory-NodeJS-Demo-Server/shmnode
gyp ERR! node -v v12.21.0
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok

**Comment by SabeehKhan18** [comment]
My target is a embedded linux 64 bit processor, but I've tried the same on my Ubuntu 18.04 machine (64bit) with the same result.

**Comment by jsr1611** [comment]
So, what was the outcome of this issue? It is still relevant. This same error still pops up in ubuntu 22.04 with node v20.
